name: Hoge App tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./src/
    strategy:
      matrix:
        node-version: [19.x, 20.x]

    env:
      SUPER_SECRET: ${{secrets.SUPER_SECRET}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run install
        uses: npm install

      - name: Run tests
        run: npm test
        